### ISSUE TITLE
Small Syntax Error

### ISSUE THREAD

**Issue by LordDorcon** [DaleRuneMTS/dale_reactionary#1]
Just a small typo

> I'm sorry, but errors were detected in your script. Please correct the
> errors listed below, and try again.
> 
> 
> File "game/Submods/dale_reactionary.rpy", line 19: invalid syntax
>             "DaleRuneMTS_dale_reactionary_1_6_1": "DaleRuneMTS_dale_reactionary_1_6_3";
>                                                                                        ^
>     
> 
> Ren'Py Version: Ren'Py 6.99.12.4.2187

**Comment by LordDorcon** [comment]
Nvm, you fixed it on your last version. Sorry!!

**Comment by TheSystemGuy1337** [comment]
Even then, I don't think Dale is even active anymore and has likely left the MAS community (like I did), so you would have been mostly left in the dark.
